-- BÀI 1:
SELECT MADATPHONG, MADV, SOLUONG
FROM CHI_TIET_SU_DUNG_DV
WHERE SOLUONG > 3 AND SOLUONG < 10;

-- BÀI 2:
UPDATE PHONG
SET GIAPHONG = GIAPHONG + 10
WHERE SOKHACHTOIDA > 10

-- BÀI 3:
DELETE FROM CHI_TIET_SU_DUNG_DV
WHERE MADATPHONG IN (
  SELECT MADATPHONG FROM DAT_PHONG 
  WHERE TRANGTHAIDAT='DA HUY'
 )

DELETE FROM DAT_PHONG
WHERE TRANGTHAIDAT = 'DA HUY'

-- BÀI 4:
SELECT TENKH
FROM KHACH_HANG
WHERE TENKH LIKE 'H%' OR TENKH LIKE 'NM%'
AND LEN (TENKH) < 20 ;

-- BÀI 5:
-- cách 1: 
SELECT DISTINCT TENKH
FROM KHACH_HANG

--cách 2:
SELECT TENKH
FROM KHACH_HANG
GROUP BY TENKH

-- BÀI 6:
SELECT MADV, TENDV, DONVITINH, DONGIA
FROM DICH_VU_DI_KEM
WHERE (DONVITINH = 'LON' AND DONGIA > 10000)
   OR (DONVITINH = 'CAI' AND DONGIA < 5000)

-- BÀI 7:
SELECT 
    dp.MADATPHONG, p.MAPHONG, p.LOAIPHONG, p.SOKHACHTOIDA, p.GIAPHONG,
    kh.MAKH, kh.TENKH, kh.SDT,
    dp.NGAYDAT, dp.GIOBATDAU, dp.GIOKETTHUC,
    ct.MADV, ct.SOLUONG, dv.DONGIA
FROM DAT_PHONG dp, PHONG p, KHACH_HANG kh, DICH_VU_DI_KEM dv, CHI_TIET_SU_DUNG_DV ct
WHERE 
dp.MADATPHONG=ct.MADATPHONG
AND dp.MAPHONG=p.MAPHONG
AND kh.MAKH = dp.MAKH
AND ct.MADV=dv.MADV

AND YEAR ( DP.NGAYDAT) IN (2016,2017)
AND P.GIAPHONG > 50000;

-- BÀI 8:
SELECT 
    dp.MADATPHONG, p.MAPHONG, p.LOAIPHONG , p.GIAPHONG,
    kh.TENKH,
    dp.NGAYDAT,
    p.GIAPHONG * DATEDIFF(HOUR, dp.GIOBATDAU, dp.GIOKETTHUC) As TongTienHat,
    SUM(ct.SOLUONG * dv.DONGIA) As TongTienSuDungDichVu,
    p.GIAPHONG * DATEDIFF(HOUR, dp.GIOBATDAU, dp.GIOKETTHUC) 
        + ISNULL(SUM(ct.SOLUONG * dv.DONGIA), 0) AS ThongTinThanhToan
FROM DAT_PHONG dp, PHONG p, KHACH_HANG kh, DICH_VU_DI_KEM dv, CHI_TIET_SU_DUNG_DV ct
WHERE 
dp.MAPHONG = p.MAPHONG
AND dp.MAKH = kh.MAKH
AND dp.MADATPHONG = ct.MADATPHONG
AND ct.MADV = dv.MADV
GROUP BY 
    dp.MADATPHONG, p.MAPHONG, p.LOAIPHONG, p.GIAPHONG,
    kh.TENKH, dp.NGAYDAT, dp.GIOBATDAU, dp.GIOKETTHUC;